# Copyright 2023 Touca, Inc. Subject to Apache-2.0 License.

name: touca-assets

on:
  push:
    branches:
      - main

jobs:
  upload-assets:
    name: upload-assets
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: authenticate to aws
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: upload assets to s3
        run: aws s3 sync ./docs/external/assets/ ${{ secrets.AWS_BUCKET_WEB }}/docs/external/assets/
